from datetime import datetime
from pathlib import Path

from core.cve import CVE
from core.findings import Finding
from core.risk_summary import RiskSummary


def create_report_directory() -> Path:
    reports_dir = Path("reports")
    reports_dir.mkdir(exist_ok=True)
    return reports_dir


def generate_report_filename(target: str) -> Path:
    reports_dir = create_report_directory()

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    return reports_dir / f"{target}_{timestamp}.html"


def executive_summary(target: str) -> str:
    return f"""
<div class="card">

<h2>Executive Summary</h2>

<table>

<tr>
<th>Target</th>
<td>{target}</td>
</tr>

<tr>
<th>Status</th>
<td>Scan Completed</td>
</tr>

<tr>
<th>Generated By</th>
<td>SentinelRecon</td>
</tr>

</table>

</div>
"""


def open_ports_section(services: list[dict]) -> str:

    rows = ""

    for service in services:

        rows += f"""
<tr>
<td>{service['port']}</td>
<td>{service['service']}</td>
<td>{service['product']}</td>
<td>{service['version']}</td>
</tr>
"""

    return f"""
<div class="card">

<h2>Open Ports</h2>

<table>

<tr>
<th>Port</th>
<th>Service</th>
<th>Product</th>
<th>Version</th>
</tr>

{rows}

</table>

</div>
"""


def findings_section(findings: list[Finding]) -> str:

    if not findings:

        return """
<div class="card">

<h2>Security Findings</h2>

<p>No security findings detected.</p>

</div>
"""

    rows = ""

    for finding in findings:

        rows += f"""
<tr>
<td>{finding.title}</td>
<td>{finding.severity}</td>
<td>{finding.category}</td>
<td>{finding.recommendation}</td>
</tr>
"""

    return f"""
<div class="card">

<h2>Security Findings</h2>

<table>

<tr>
<th>Title</th>
<th>Severity</th>
<th>Category</th>
<th>Recommendation</th>
</tr>

{rows}

</table>

</div>
"""


def cve_section(cves: list[CVE]) -> str:

    if not cves:

        return """
<div class="card">

<h2>Known Vulnerabilities</h2>

<p>No known CVEs found.</p>

</div>
"""

    rows = ""

    for cve in cves:

        rows += f"""
<tr>
<td>{cve.cve_id}</td>
<td>{cve.severity}</td>
<td>{cve.cvss_score}</td>
<td>{cve.published[:10]}</td>
</tr>
"""

    return f"""
<div class="card">

<h2>Known Vulnerabilities</h2>

<table>

<tr>
<th>CVE ID</th>
<th>Severity</th>
<th>CVSS</th>
<th>Published</th>
</tr>

{rows}

</table>

</div>
"""


def risk_summary_section(summary: RiskSummary) -> str:

    return f"""
<div class="card">

<h2>Risk Summary</h2>

<table>

<tr>
<th>Critical</th>
<td>{summary.critical}</td>
</tr>

<tr>
<th>High</th>
<td>{summary.high}</td>
</tr>

<tr>
<th>Medium</th>
<td>{summary.medium}</td>
</tr>

<tr>
<th>Low</th>
<td>{summary.low}</td>
</tr>

<tr>
<th>Informational</th>
<td>{summary.informational}</td>
</tr>

<tr>
<th>Total CVEs</th>
<td>{summary.total}</td>
</tr>

<tr>
<th>Average CVSS</th>
<td>{summary.average_cvss}</td>
</tr>

<tr>
<th>Overall Risk</th>
<td><strong>{summary.overall_risk}</strong></td>
</tr>

</table>

</div>
"""


def generate_html_report(
    target: str,
    services: list[dict],
    findings: list[Finding],
    cves: list[CVE],
    summary: RiskSummary,
) -> Path:

    report_path = generate_report_filename(target)

    html = f"""
<!DOCTYPE html>

<html lang="en">

<head>

<meta charset="UTF-8">

<title>SentinelRecon Report</title>

<style>

body {{
    font-family: Arial, Helvetica, sans-serif;
    background: #f4f6f9;
    margin: 40px;
}}

.container {{
    max-width: 1100px;
    margin: auto;
}}

.card {{
    background: white;
    padding: 20px;
    margin-bottom: 20px;
    border-radius: 10px;
    box-shadow: 0 2px 8px rgba(0,0,0,.08);
}}

table {{
    width: 100%;
    border-collapse: collapse;
}}

th, td {{
    border: 1px solid #ddd;
    padding: 10px;
    text-align: left;
}}

th {{
    background: #0b5394;
    color: white;
}}

.footer {{
    margin-top: 30px;
    color: gray;
}}

</style>

</head>

<body>

<div class="container">

<h1>SentinelRecon Scan Report</h1>

{executive_summary(target)}

{open_ports_section(services)}

{findings_section(findings)}

{cve_section(cves)}

{risk_summary_section(summary)}

<div class="footer">

Generated by SentinelRecon

</div>

</div>

</body>

</html>
"""

    report_path.write_text(html, encoding="utf-8")

    return report_path